### ISSUE TITLE
create a readme for this repo.

### ISSUE THREAD

**Issue by adamshamsudeen** [adamshamsudeen/opencv-flask#1]

**Comment by susw12** [comment]
What exactly does this app do?

**Comment by susw12** [comment]
What exactly does this app do?

**Comment by adamshamsudeen** [comment]
Flask app to create images with banners. Like the one found in facebook.

**Comment by 0x48piraj** [comment]
On it !

**Comment by 0x48piraj** [comment]
Done, Pull Request is waiting :heart_eyes: :
